In [5]:
import pandas as pdנ
df = pd.read_csv('sport_athletes.csv')

df.rename(columns={
    'Height(cm)': 'Height',
    'Weight(kg)': 'Weight',
    'Wins': 'Wins'
}, inplace=True)

stats = df.groupby('Sport Type').agg({
    'Weight': 'max',
    'Height': 'max',
    'Wins': 'max'
})

print("Statistics by Sport Type (Max Weight, Height, Wins):")
print(stats)

Statistics by Sport Type (Max Weight, Height, Wins):
                 Weight  Height  Wins
Sport Type
Basketball          147     216     3
Cycling              72     186     5
Gymnastics           52     160     5
Soccer               83     187     3
Swimming             90     200     5
Tennis               85     188     4
Track and Field      94     195     6

In [7]:
min_weights = df.groupby('Sport Type')['Weight'].min().sort_values()
print("\nMinimum weight by Sport Type (Ascending):")
print(min_weights)

Minimum weight by Sport Type (Ascending):
Sport Type
Gymnastics         45
Soccer             57
Track and Field    57
Swimming           58
Cycling            68
Tennis             70
Basketball         96
Name: Weight, dtype: int64

In [9]:
tallest_by_sport = df.loc[df.groupby('Sport Type')['Height'].idxmax()]
print("\nTallest participants by Sport Type:")
print(tallest_by_sport[['Sport Type', 'Athlete Name', 'Height']])

Tallest participants by Sport Type:
         Sport Type       Athlete Name  Height
4        Basketball   Shaquille O'Neal     216
28          Cycling      Primoz Roglic     186
33       Gymnastics        Aly Raisman     160
7            Soccer  Cristiano Ronaldo     187
15         Swimming           Sun Yang     200
19           Tennis     Novak Djokovic     188
20  Track and Field         Usain Bolt     195

In [11]:
grouped = df.groupby(['Country', 'Sport Type'])
# a
max_stats = grouped.max()
print("\nMax Statistics by Country and Sport Type:")
print(max_stats)
# b
basketball_usa = grouped.get_group(('USA', 'Basketball')).max()
print("\nMax Statistics for Basketball in USA:")
print(basketball_usa)
# c
football_stats = df[df['Sport Type'] == 'Soccer']
print("\nStatistics for Soccer:")
print(football_stats)
# d
filtered_sports = df[df['Sport Type'].isin(['Tennis', 'Soccer'])]
print("\nStatistics for Tennis and Soccer:")
print(filtered_sports)
# e
reordered = df.set_index(['Sport Type', 'Country']).sort_index(level=['Country', 'Sport Type'], ascending=[False, False])
print("\nReordered by Sport and Country:")
print(reordered)
# f
agg_stats = grouped[['Wins', 'Height']].agg(['mean', 'std', 'max', 'min'])
print("\nAggregated Statistics (Wins and Height):")
print(agg_stats)

Max Statistics by Country and Sport Type:
                                     Athlete Name  Height  Weight  Wins  \
Country     Sport Type
Argentina   Soccer                   Lionel Messi     170      69     2
Australia   Swimming                   Ian Thorpe     196      85     4
Belgium     Cycling                   Eddy Merckx     181      72     5
Brazil      Soccer                           Pelé     174      72     3
China       Swimming                     Sun Yang     200      90     3
France      Soccer                Zinedine Zidane     185      80     3
Jamaica     Track and Field            Usain Bolt     195      94     6
Netherlands Cycling          Anna van der Breggen     175      68     4
Portugal    Soccer              Cristiano Ronaldo     187      83     2
Romania     Gymnastics             Nadia Comaneci     155      50     5
Serbia      Tennis                 Novak Djokovic     188      84     4
Slovenia    Cycling                 Tadej Pogacar     186      69     3
Spain       Tennis                   Rafael Nadal     185      85     3
Switzerland Tennis                  Roger Federer     185      85     2
UK          Cycling                Geraint Thomas     183      71     4
            Track and Field              Mo Farah     176      65     5
USA         Basketball           Shaquille O'Neal     216     147     3
            Gymnastics               Simone Biles     160      52     5
            Soccer                  Megan Rapinoe     168      62     2
            Swimming               Michael Phelps     193      88     5
            Tennis                Serena Williams     175      70     4
            Track and Field     Florence Griffith     188      81     4

                            Olympic Date
Country     Sport Type
Argentina   Soccer            11/08/2016
Australia   Swimming          11/08/2000
Belgium     Cycling           15/08/1980
Brazil      Soccer            18/08/1970
China       Swimming          08/08/2012
France      Soccer            17/08/1998
Jamaica     Track and Field   22/08/2012
Netherlands Cycling           10/08/2020
Portugal    Soccer            25/08/2008
Romania     Gymnastics        18/08/1976
Serbia      Tennis            10/08/2020
Slovenia    Cycling           11/08/2020
Spain       Tennis            05/08/2016
Switzerland Tennis            28/07/2008
UK          Cycling           08/08/2012
            Track and Field   05/08/2016
USA         Basketball        24/08/2012
            Gymnastics        15/08/2008
            Soccer            05/08/2020
            Swimming          25/08/2012
            Tennis            01/08/2012
            Track and Field   18/08/1988

Max Statistics for Basketball in USA:
Country                      USA
Sport Type            Basketball
Athlete Name    Shaquille O'Neal
Height                       216
Weight                       147
Wins                           3
Olympic Date          24/08/2012
dtype: object

Statistics for Soccer:
      Country Sport Type       Athlete Name  Height  Weight  Wins Olympic Date
5      Brazil     Soccer               Pelé     174      72     3   18/08/1970
6      Brazil     Soccer              Marta     163      57     3   01/08/2004
7    Portugal     Soccer  Cristiano Ronaldo     187      83     2   25/08/2008
8   Argentina     Soccer       Lionel Messi     170      69     2   11/08/2016
9      France     Soccer    Zinedine Zidane     185      80     3   17/08/1998
10        USA     Soccer      Megan Rapinoe     168      62     2   05/08/2020

Statistics for Tennis and Soccer:
        Country Sport Type       Athlete Name  Height  Weight  Wins  \
5        Brazil     Soccer               Pelé     174      72     3
6        Brazil     Soccer              Marta     163      57     3
7      Portugal     Soccer  Cristiano Ronaldo     187      83     2
8     Argentina     Soccer       Lionel Messi     170      69     2
9        France     Soccer    Zinedine Zidane     185      80     3
10          USA     Soccer      Megan Rapinoe     168      62     2
16  Switzerland     Tennis      Roger Federer     185      85     2
17          USA     Tennis    Serena Williams     175      70     4
18        Spain     Tennis       Rafael Nadal     185      85     3
19       Serbia     Tennis     Novak Djokovic     188      84     4

   Olympic Date
5    18/08/1970
6    01/08/2004
7    25/08/2008
8    11/08/2016
9    17/08/1998
10   05/08/2020
16   28/07/2008
17   01/08/2012
18   05/08/2016
19   10/08/2020

Reordered by Sport and Country:
                                     Athlete Name  Height  Weight  Wins  \
Sport Type      Country
Track and Field USA                    Carl Lewis     188      81     4
                USA             Florence Griffith     165      57     4
                USA                  Ashton Eaton     185      77     3
Tennis          USA               Serena Williams     175      70     4
Swimming        USA                Michael Phelps     193      88     5
                USA                 Katie Ledecky     180      58     4
                USA                Caeleb Dressel     191      88     3
Soccer          USA                 Megan Rapinoe     168      62     2
Gymnastics      USA                  Simone Biles     142      48     5
                USA                   Aly Raisman     160      52     3
                USA                 Shawn Johnson     157      50     3
                USA                 Gabby Douglas     150      45     3
Basketball      USA                Michael Jordan     198      98     3
                USA                  LeBron James     206     113     2
                USA                   Kobe Bryant     198      96     2
                USA                  Kevin Durant     208     109     3
                USA              Shaquille O'Neal     216     147     1
Track and Field UK                       Mo Farah     176      65     5
Cycling         UK                   Chris Froome     180      70     4
                UK                 Geraint Thomas     183      71     4
Tennis          Switzerland         Roger Federer     185      85     2
                Spain                Rafael Nadal     185      85     3
Cycling         Slovenia            Tadej Pogacar     184      69     3
                Slovenia            Primoz Roglic     186      68     3
Tennis          Serbia             Novak Djokovic     188      84     4
Gymnastics      Romania            Nadia Comaneci     155      50     5
Soccer          Portugal        Cristiano Ronaldo     187      83     2
Cycling         Netherlands  Anna van der Breggen     175      68     4
Track and Field Jamaica                Usain Bolt     195      94     6
Soccer          France            Zinedine Zidane     185      80     3
Swimming        China                    Sun Yang     200      90     3
Soccer          Brazil                       Pelé     174      72     3
                Brazil                      Marta     163      57     3
Cycling         Belgium               Eddy Merckx     181      72     5
Swimming        Australia              Ian Thorpe     196      85     4
Soccer          Argentina            Lionel Messi     170      69     2

                            Olympic Date
Sport Type      Country
Track and Field USA           15/08/1984
                USA           18/08/1988
                USA           08/08/2016
Tennis          USA           01/08/2012
Swimming        USA           16/08/2004
                USA           25/08/2012
                USA           06/08/2016
Soccer          USA           05/08/2020
Gymnastics      USA           05/08/2016
                USA           10/08/2012
                USA           15/08/2008
                USA           11/08/2016
Basketball      USA           08/08/1992
                USA           15/08/2008
                USA           24/08/2012
                USA           10/08/2016
                USA           22/08/2000
Track and Field UK            05/08/2016
Cycling         UK            08/08/2012
                UK            08/08/2008
Tennis          Switzerland   28/07/2008
                Spain         05/08/2016
Cycling         Slovenia      11/08/2020
                Slovenia      05/08/2016
Tennis          Serbia        10/08/2020
Gymnastics      Romania       18/08/1976
Soccer          Portugal      25/08/2008
Cycling         Netherlands   10/08/2020
Track and Field Jamaica       22/08/2012
Soccer          France        17/08/1998
Swimming        China         08/08/2012
Soccer          Brazil        18/08/1970
                Brazil        01/08/2004
Cycling         Belgium       15/08/1980
Swimming        Australia     11/08/2000
Soccer          Argentina     11/08/2016

Aggregated Statistics (Wins and Height):
                                 Wins                       Height             \
                                 mean      std max min        mean        std
Country     Sport Type
Argentina   Soccer           2.000000      NaN   2   2  170.000000        NaN
Australia   Swimming         4.000000      NaN   4   4  196.000000        NaN
Belgium     Cycling          5.000000      NaN   5   5  181.000000        NaN
Brazil      Soccer           3.000000  0.00000   3   3  168.500000   7.778175
China       Swimming         3.000000      NaN   3   3  200.000000        NaN
France      Soccer           3.000000      NaN   3   3  185.000000        NaN
Jamaica     Track and Field  6.000000      NaN   6   6  195.000000        NaN
Netherlands Cycling          4.000000      NaN   4   4  175.000000        NaN
Portugal    Soccer           2.000000      NaN   2   2  187.000000        NaN
Romania     Gymnastics       5.000000      NaN   5   5  155.000000        NaN
Serbia      Tennis           4.000000      NaN   4   4  188.000000        NaN
Slovenia    Cycling          3.000000  0.00000   3   3  185.000000   1.414214
Spain       Tennis           3.000000      NaN   3   3  185.000000        NaN
Switzerland Tennis           2.000000      NaN   2   2  185.000000        NaN
UK          Cycling          4.000000  0.00000   4   4  181.500000   2.121320
            Track and Field  5.000000      NaN   5   5  176.000000        NaN
USA         Basketball       2.200000  0.83666   3   1  205.200000   7.563068
            Gymnastics       3.500000  1.00000   5   3  152.250000   8.015610
            Soccer           2.000000      NaN   2   2  168.000000        NaN
            Swimming         4.000000  1.00000   5   3  188.000000   7.000000
            Tennis           4.000000      NaN   4   4  175.000000        NaN
            Track and Field  3.666667  0.57735   4   3  179.333333  12.503333


                             max  min
Country     Sport Type
Argentina   Soccer           170  170
Australia   Swimming         196  196
Belgium     Cycling          181  181
Brazil      Soccer           174  163
China       Swimming         200  200
France      Soccer           185  185
Jamaica     Track and Field  195  195
Netherlands Cycling          175  175
Portugal    Soccer           187  187
Romania     Gymnastics       155  155
Serbia      Tennis           188  188
Slovenia    Cycling          186  184
Spain       Tennis           185  185
Switzerland Tennis           185  185
UK          Cycling          183  180
            Track and Field  176  176
USA         Basketball       216  198
            Gymnastics       160  142
            Soccer           168  168
            Swimming         193  180
            Tennis           175  175
            Track and Field  188  165

In [13]:
new_rows = pd.DataFrame({
    'Country': ['Canada', 'USA'],
    'Sport Type': ['Hockey', 'Skiing'],
    'Athlete Name': ['Wayne Gretzky', 'Lindsey Vonn'],
    'Height': [183, 172],
    'Weight': [84, 68],
    'Wins': [3, 4],
    'Olympic Date': ['01/02/2002', '12/02/2010']
})
df = pd.concat([df, new_rows], ignore_index=True)

print("\nDataFrame after adding new rows:")
print(df)

DataFrame after adding new rows:
        Country       Sport Type          Athlete Name  Height  Weight  Wins  \
0           USA       Basketball        Michael Jordan     198      98     3
1           USA       Basketball          LeBron James     206     113     2
2           USA       Basketball           Kobe Bryant     198      96     2
3           USA       Basketball          Kevin Durant     208     109     3
4           USA       Basketball      Shaquille O'Neal     216     147     1
5        Brazil           Soccer                  Pelé     174      72     3
6        Brazil           Soccer                 Marta     163      57     3
7      Portugal           Soccer     Cristiano Ronaldo     187      83     2
8     Argentina           Soccer          Lionel Messi     170      69     2
9        France           Soccer       Zinedine Zidane     185      80     3
10          USA           Soccer         Megan Rapinoe     168      62     2
11          USA         Swimming        Michael Phelps     193      88     5
12          USA         Swimming         Katie Ledecky     180      58     4
13          USA         Swimming        Caeleb Dressel     191      88     3
14    Australia         Swimming            Ian Thorpe     196      85     4
15        China         Swimming              Sun Yang     200      90     3
16  Switzerland           Tennis         Roger Federer     185      85     2
17          USA           Tennis       Serena Williams     175      70     4
18        Spain           Tennis          Rafael Nadal     185      85     3
19       Serbia           Tennis        Novak Djokovic     188      84     4
20      Jamaica  Track and Field            Usain Bolt     195      94     6
21          USA  Track and Field            Carl Lewis     188      81     4
22           UK  Track and Field              Mo Farah     176      65     5
23          USA  Track and Field     Florence Griffith     165      57     4
24          USA  Track and Field          Ashton Eaton     185      77     3
25           UK          Cycling          Chris Froome     180      70     4
26      Belgium          Cycling           Eddy Merckx     181      72     5
27     Slovenia          Cycling         Tadej Pogacar     184      69     3
28     Slovenia          Cycling         Primoz Roglic     186      68     3
29           UK          Cycling        Geraint Thomas     183      71     4
30  Netherlands          Cycling  Anna van der Breggen     175      68     4
31          USA       Gymnastics          Simone Biles     142      48     5
32      Romania       Gymnastics        Nadia Comaneci     155      50     5
33          USA       Gymnastics           Aly Raisman     160      52     3
34          USA       Gymnastics         Shawn Johnson     157      50     3
35          USA       Gymnastics         Gabby Douglas     150      45     3
36       Canada           Hockey         Wayne Gretzky     183      84     3
37          USA           Skiing          Lindsey Vonn     172      68     4

   Olympic Date
0    08/08/1992
1    15/08/2008
2    24/08/2012
3    10/08/2016
4    22/08/2000
5    18/08/1970
6    01/08/2004
7    25/08/2008
8    11/08/2016
9    17/08/1998
10   05/08/2020
11   16/08/2004
12   25/08/2012
13   06/08/2016
14   11/08/2000
15   08/08/2012
16   28/07/2008
17   01/08/2012
18   05/08/2016
19   10/08/2020
20   22/08/2012
21   15/08/1984
22   05/08/2016
23   18/08/1988
24   08/08/2016
25   08/08/2012
26   15/08/1980
27   11/08/2020
28   05/08/2016
29   08/08/2008
30   10/08/2020
31   05/08/2016
32   18/08/1976
33   10/08/2012
34   15/08/2008
35   11/08/2016
36   01/02/2002
37   12/02/2010

In [19]:
df['Olympic Date'] = pd.to_datetime(df['Olympic Date'], errors='coerce')

df.dropna(subset=['Olympic Date'], inplace=True)

wins_by_year = df.groupby(df['Olympic Date'].dt.year)['Wins'].sum()
print("\nWins by Year:")
print(wins_by_year)

Wins by Year:
Olympic Date
1992     3
2000     4
2002     3
2004     3
2008     4
2010     4
2012    14
2016    30
2020    13
Name: Wins, dtype: int64

In [21]:
# איחוד הטבלאות כך שיופיעו רק ספורטאים שעבורם יש תיעוד אם הם מעשנים (Inner Join)
merged_only_smokers = pd.merge(df, smoking_df, how='inner', on='Athlete Name')
print("\nMerged Table (Smokers Only):")
print(merged_only_smokers)

# איחוד הטבלאות כך שיופיעו כל הספורטאים, ותיעוד של עישון אם קיים (Outer Join)
merged_all_athletes = pd.merge(df, smoking_df, how='outer', on='Athlete Name')
print("\nMerged Table (All Athletes with Smoking Data):")
print(merged_all_athletes)

NameError: name 'smoking_df' is not defined